title: Los Santos Sheriff's Police Department - Scanner
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This scanner page provides live tracked information to the Los
    Santos Sheriff's Department calls and situations ongoing.
  systems:
    - name: Sheriff's Department Website
      description: ""
      link: https://lssd.gta.world
  dateFormat: January 2, 2006 at 14:45
  disqusShortname: ""
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about the <a class='text-grey-darkest'
    title='Visit Main Site' href='https://lssd.gta.world'>Los Santos Sheriff's
    Department</a> operations and ongoing incidents.<br />Follow us <a
    class='text-grey-darkest' title='Visit our page on FaceBrowser'
    href='https://face.gta.world/pages/lscosheriff'>on FaceBrowser</a>. <br />
    <a class='text-grey-darkest' href='%s' >Subscribe to RSS</a><br />to be
    alerted of new events.
  copyrightHolder: Los Santos Sheriff's Department
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: >-
    GTA World is not affiliated with or endorsed by Rockstar North, Take-Two
    Interactive or other rightsholders. Any trademarks used belong to their
    respective owners. GTA WORLD reserves all rights on rightly owned images and
    other visual content provided on GTA.WORLD.

    <br/>

    This website was created using a framework called clearstatus, view the source code of the website <a class='text-grey-darkest' title='Visit GitHub' href='https://github.com/biscuitgtaw/clearstatus'>here.</a>
